export const FOREX_TICKERS = [
  'AUDCAD', 'AUDCHF', 'AUDJPY', 'AUDNZD', 'AUDUSD',
  'CADCHF', 'CADJPY', 'CHFJPY', 'EURAUD', 'EURCAD',
  'EURCHF', 'EURGBP', 'EURJPY', 'EURNZD', 'EURRUB',
  'EURSGD', 'EURUSD', 'GBPAUD', 'GBPCAD', 'GBPCHF',
  'GBPJPY', 'GBPNZD', 'GBPUSD', 'NZDCAD', 'NZDCHF',
  'NZDJPY', 'NZDUSD', 'USDCAD', 'USDCHF', 'USDCNY',
  'USDHKD', 'USDILS', 'USDINR', 'USDJPY', 'USDMXN',
  'USDPLN', 'USDRUB', 'USDSGD', 'USDTRY', 'USDZAR'
]

export const CRYPTO_TICKERS = [
  'IDUSD', 'OPUSD', 'ADAUSD', 'APEUSD', 'APTUSD',
  'ARBUSD', 'AXSUSD', 'BCHUSD', 'BNBUSD', 'BTCUSD',
  'BTTUSD', 'CFXUSD', 'CHZUSD', 'DOTUSD', 'DYMUSD',
  'EOSUSD', 'ERDUSD', 'ETCUSD', 'ETHUSD', 'FILUSD',
  'FTMUSD', 'FTTUSD', 'GRTUSD', 'HFTUSD', 'ICPUSD',
  'INJUSD', 'IOTUSD', 'JTOUSD', 'LDOUSD', 'LTCUSD',
  'MKRUSD', 'NEOUSD', 'NOTUSD', 'ONTUSD', 'QNTUSD',
  'RIFUSD', 'SEIUSD', 'SNXUSD', 'SOLUSD', 'STXUSD',
  'SUIUSD', 'SXPUSD', 'TIAUSD', 'TONUSD', 'TRXUSD',
  'TWTUSD', 'UNIUSD', 'VETUSD', 'WIFUSD', 'WLDUSD',
  'XECUSD', 'XLMUSD', 'XMRUSD', 'XRPUSD', 'XTZUSD',
  'YFIUSD', 'ZECUSD', 'AAVEUSD', 'ALGOUSD', 'ATOMUSD',
  'AVAXUSD', 'BANDUSD', 'BLURUSD', 'BONKUSD', 'CAKEUSD',
  'DASHUSD', 'DOGEUSD', 'EGLDUSD', 'FLOWUSD', 'GALAUSD',
  'HBARUSD', 'KAVAUSD', 'KLAYUSD', 'LINKUSD', 'LUNAUSD',
  'LUNCUSD', 'MANAUSD', 'MEMEUSD', 'NEARUSD', 'ORDIUSD',
  'PAXGUSD', 'PEPEUSD', 'QTUMUSD', 'RUNEUSD', 'SANDUSD',
  'SHIBUSD', 'FLOKIUSD', 'MANTAUSD', 'MATICUSD', 'OCEANUSD',
  'THETAUSD', 'WAVESUSD', 'PENDLEUSD'
]

export const INITIAL_VISIBLE_ROWS = 15
export const LOAD_MORE_COUNT = 10

