export const marketWatchCrypto = [
    [
        'ID',
        'OP',
        'Cardano',
        'Ape Coin',
        'Aptos',
        'ARB',
        'Axie Infinity',
        'Bitcoin Cash',
        'Binance Coin',
        'Bitcoin',
        'Bittorent',
        'CFX',
        'Chiliz',
        'Polkadot',
        'DYM',
        'ECSO',
        'Elrond',
        'Ethereum Classic',
        'Ethereum',
        'Filecoin',
        'Fantom',
        'FTX',
        'The Graph',
        'Hashflow',
        'Internet Comp',
        'INJ',
        'IOTA',
        'JTO',
        'Lido DAO',
        'Litecoin',
        'Maker',
        'NEO',
        'Notcoin',
        'Ontology',
        'Quant',
        'RIF',
        'SEI',
        'Synthetics Network',
        'Solana',
        'Stacks',
        'SUI',
        'Swipe',
        'Celestia',
        'Toncoin',
        'Tron',
        'Trust Wallet',
        'Uniswap',
        'VeChain',
        'DogWifHat',
        'Worldcoin',
        'eCash',
        'Stellar',
        'Monero',
        'Ripple',
        'Tezos',
        'Yearn Finance',
        'ZCash',
        'Aave',
        'Algorand',
        'Cosmos',
        'Avalanche',
        'Band',
        'BLUR',
        'Bonk',
        'PancakeSwap',
        'Dash',
        'Dogecoin',
        'MultiversX',
        'Flow',
        'Gala',
        'Hedera',
        'Kava',
        'Klaytn',
        'Chainlink',
        'Terra',
        'Terra Classic',
        'Decentraland',
        'Meme',
        'NEAR',
        'ORDI',
        'PAX Gold',
        'Pepe',
        'Qtum',
        'THORChain',
        'The sandbox',
        'Shiba Inu',
        'Floki',
        'MANTA',
        'Polygon',
        'Ocean Protocol',
        'Theta',
        'Waves',
        'PENDLE'
    ],
    [
        'IDUSD',
        'OPUSD',
        'ADAUSD',
        'APEUSD',
        'APTUSD',
        'ARBUSD',
        'AXSUSD',
        'BCHUSD',
        'BNBUSD',
        'BTCUSD',
        'BTTUSD',
        'CFXUSD',
        'CHZUSD',
        'DOTUSD',
        'DYMUSD',
        'EOSUSD',
        'ERDUSD',
        'ETCUSD',
        'ETHUSD',
        'FILUSD',
        'FTMUSD',
        'FTTUSD',
        'GRTUSD',
        'HFTUSD',
        'ICPUSD',
        'INJUSD',
        'IOTUSD',
        'JTOUSD',
        'LDOUSD',
        'LTCUSD',
        'MKRUSD',
        'NEOUSD',
        'NOTUSD',
        'ONTUSD',
        'QNTUSD',
        'RIFUSD',
        'SEIUSD',
        'SNXUSD',
        'SOLUSD',
        'STXUSD',
        'SUIUSD',
        'SXPUSD',
        'TIAUSD',
        'TONUSD',
        'TRXUSD',
        'TWTUSD',
        'UNIUSD',
        'VETUSD',
        'WIFUSD',
        'WLDUSD',
        'XECUSD',
        'XLMUSD',
        'XMRUSD',
        'XRPUSD',
        'XTZUSD',
        'YFIUSD',
        'ZECUSD',
        'AAVEUSD',
        'ALGOUSD',
        'ATOMUSD',
        'AVAXUSD',
        'BANDUSD',
        'BLURUSD',
        'BONKUSD',
        'CAKEUSD',
        'DASHUSD',
        'DOGEUSD',
        'EGLDUSD',
        'FLOWUSD',
        'GALAUSD',
        'HBARUSD',
        'KAVAUSD',
        'KLAYUSD',
        'LINKUSD',
        'LUNAUSD',
        'LUNCUSD',
        'MANAUSD',
        'MEMEUSD',
        'NEARUSD',
        'ORDIUSD',
        'PAXGUSD',
        'PEPEUSD',
        'QTUMUSD',
        'RUNEUSD',
        'SANDUSD',
        'SHIBUSD',
        'FLOKIUSD',
        'MANTAUSD',
        'MATICUSD',
        'OCEANUSD',
        'THETAUSD',
        'WAVESUSD',
        'PENDLEUSD'
    ],
    ['Crypto']
]
export const marketWatchStocks = [
    ['Citigroup',
    'Ford',
    'AT&T',
    'Visa',
    'Alcoa',
    'C3.ai Inc',
    'Boeing',
    'Brunswick Corp',
    'Bloom Energy Corp',
    'BP',
    'Canadian Imperial Bank of Commerce',
    'Dollar General',
    'Estée Lauder',
    'Facebook',
    'Total',
    'Gen. Electric',
    'Globe Life Inc',
    'General Motors Company',
    'Goldman Sachs',
    'Home Depot',
    'Coca-Cola',
    'Li Auto Inc',
    'MasterCard',
    'Altria Group',
    'Morgan Stanley ',
    'Micron Technology Inc',
    'Procter & Gamble',
    'Philip Morris',
    'QuantumScape Corporation',
    'Royal Bank Of Canada',
    'Suncor Energy Inc',
    'Toronto-Dominion Bank',
    'Toyota',
    'Verizon',
    'Zoom',
    'American Airlines Group Inc.',
    'Aurora Cannabis',
    'Arca internation market',
    'Adidas',
    'Agnico Eagle Mines Ltd',
    'AIG',
    'Airbus',
    'Albemarle',
    'Aristocrat Leisure Ltd',
    'Autoliv inc',
    'AMD',
    'Air Products and Chemicals Inc',
    'Arm Holdings plc',
    'Amer. Express',
    'Axis Capital Holdings Limited',
    'Astrazeneca',
    'Bank of America',
    'BASF',
    'BlackRock, Inc.',
    'Bank Of Montreal',
    'BMW',
    'BNP Paribas',
    'Bank Nova Scotia Halifax Pfd 3',
    'B2Gold Corp',
    'Caterpillar',
    'Carnival',
    'Canopy Growth',
    'Chevron',
    'Canadian Natural Resources Ltd',
    'Salesforce',
    'Cenovus Energy Inc',
    'CVS Health Corporation',
    'Daimler',
    'Delta Airlines',
    'Deutsche Bank',
    'Dropbox',
    'Disney',
    'Dominos Pizza',
    'Endeavor Group Holdings, Inc',
    'Enbridge Inc',
    'Eni',
    'FedEx',
    'GameStop Corporation',
    'Harley-Davidson',
    'Hewlett-Packard',
    'IBM',
    'Imperial Oil Ltd',
    'Inovio Pharmaceuticals, Inc.',
    'Inditex',
    'J&J',
    'JPMorgan Chase',
    'Kinross Gold Corp',
    'CarMax',
    'Lithium Americas Corp',
    'Lennar Corporation',
    'Linde PLC',
    'Eli Lilly and Company',
    'Lockheed Martin',
    'Lloyds Banking',
    'McDonalds',
    'Medtronic PLC',
    'Magna International, Inc',
    '3M',
    'Merck & Company, Inc',
    'MTS',
    'Newmont Mining Corporation',
    'Cloudflare, Inc.',
    'Nio',
    'Nike',
    'Northrop Grumman',
    'Nokia Corporation',
    'Nutrien Ltd',
    'Pembina Pipeline Corp',
    'PepsiCo',
    'Pfizer',
    'Piedmont Lithium Inc',
    'PVH',
    'RBC Bearings Inc',
    'Royal Caribbean Cruises Ltd',
    'Rio Tinto Plc',
    'Raytheon Technologies',
    'SAP',
    'Sotera Health',
    'Siemens',
    'J.M. Smucker Company',
    'Standard Lithium Ltd',
    'Sociedad Química y Minera de Chile',
    'Constellation Brands, Inc.',
    'Symbotic Inc',
    'Telstra Corporation Ltd',
    'TPG Inc',
    'TC Energy Corp',
    'Travelers',
    'Taiwan Semiconductor Manufacturing Co Ltd',
    'Tyson Foods',
    'UnitedHealth',
    'VF Corp',
    'Vanguard Information Tech ETF',
    'Vodafone',
    'Volkswagen',
    'Wallbox N.V',
    'WOODSIDE ENERGY GROUP LTD',
    'Wells Fargo',
    'Walmart',
    'Exxon Mobil',
    'Apple',
    'AbbVie',
    'Airbnb Inc',
    'Acrivon Therapeutics Inc',
    'Adobe',
    'Aeroflot',
    'Alrosa',
    'Amgen Inc',
    'Amazon',
    'ASML Holding NV',
    'ASP Isotopes Inc',
    'Atour Lifestyle Holdings Ltd',
    'Broadcom inc',
    'Alibaba',
    'Bayer',
    'Brown Forman Inc',
    'Baidu',
    'Biogen Inc',
    'Booking.com',
    'Blacksky Technology Inc',
    'Ballard Power Sys',
    'BionTech SE',
    'Beyond, Inc.',
    'ChargePoint Holdings, Inc',
    'Coinbase Global, Inc.',
    'Teucrium Corn Fund',
    'Costco Wholesale Corp',
    'Cisco',
    'Dell Technologies Inc.',
    'Digital World Acquisition Corp',
    'eBay',
    'American Green',
    'Elbit Systems Ltd.',
    'Fastly, Inc.',
    'Gazprom',
    'Grayscale',
    'Gilead Sciences',
    'Nornickel',
    'Genelux Corp',
    'Barrick Gold Corp',
    'Fusion Fuel Sys',
    'iShares Bitcoin Trust',
    'Interactive Brokers Group, Inc.',
    'Intel',
    'Jumia Technologies AG',
    'Juventus',
    'Knightscope Inc',
    'Kyverna Therapeutics, Inc.',
    'Luminar Technologies Inc',
    'Lucid Group inc',
    'Lukoil',
    'Lululemon Athletica Inc',
    'Lyft',
    'Manchester United Plc',
    'Mustang Bio, Inc.',
    'Moderna',
    'Marvell Technology inc',
    'MSFT',
    'MicroStrategy',
    'Nasdaq, Inc.',
    'Netflix',
    'Nikola Corporation',
    'Novavax Inc',
    'Nvidia',
    'Novatek',
    'Oracle',
    'Pinterest',
    'Palantir technologies inc',
    'Plug Power',
    'PayPal',
    'Qualcomm',
    'Ferrari',
    'REPSOL',
    'Sberbank',
    'Starbucks',
    'Southern Copper Corporation',
    'Sigma Lithium Corporation',
    'Sirius XM Holdings Inc.',
    'SiTime Corporation',
    'Super Micro Computer Inc',
    'Snail Inc',
    'Snapchat',
    'Sony Group Corporation',
    'SoundHound AI, Inc',
    'Virgin Galactic Holdings, Inc.',
    'Spotify',
    'Skyworks Solutions inc',
    'Teck Resources Ltd',
    'Alkermes',
    'Tilray',
    'TripAdvisor',
    'Tesla',
    'Uber',
    'Ulta Beauty, Inc.',
    'ProShares Ultra VIX Short-Term Futures ETF',
    'Vale',
    'Bank VTB',
    'Vaxart, Inc',
    'Westport Fuel Sys',
    'Wynn Resorts',
    'Yandex',
    'ARC Resources Ltd',
    'Berkshire Hathaway inc',
    'FendX Technologies Inc',
    'Alphabet'
    ],
    [
        'C',
        'F',
        'T',
        'V',
        'AA',
        'AI',
        'BA',
        'BC',
        'BE',
        'BP',
        'CM',
        'DG',
        'EL',
        'META',
        'FP',
        'GE',
        'GL',
        'GM',
        'GS',
        'HD',
        'KO',
        'LI',
        'MA',
        'MO',
        'MS',
        'MU',
        'PG',
        'PM',
        'QS',
        'RY',
        'SU',
        'TD',
        'TM',
        'VZ',
        'ZM',
        'AAL',
        'ACB',
        'ADR',
        'ADDYY',
        'AEM',
        'AIG',
        'AIR',
        'ALB',
        'ALL',
        'ALV',
        'AMD',
        'APD',
        'ARM',
        'AXP',
        'AXS',
        'AZN',
        'BAC',
        'BAS',
        'BLK',
        'BMO',
        'BMW',
        'BNP',
        'BNS',
        'BTG',
        'CAT',
        'CCL',
        'CGC',
        'CHV',
        'CNQ',
        'CRM',
        'CVE',
        'CVS',
        'DAI',
        'DAL',
        'DBK',
        'DBX',
        'DIS',
        'DPZ',
        'EDR',
        'ENB',
        'ENI',
        'FDX',
        'GME',
        'HOG',
        'HPQ',
        'IBM',
        'IMO',
        'INO',
        'IDEXF',
        'JNJ',
        'JPM',
        'KGC',
        'KMX',
        'LAC',
        'LEN',
        'LIN',
        'LLY',
        'LMT',
        'LYG',
        'MCD',
        'MDT',
        'MGA',
        'MMM',
        'MRK',
        'MTS',
        'NEM',
        'NET',
        'NIO',
        'NKE',
        'NOC',
        'NOK',
        'NTR',
        'PBA',
        'PEP',
        'PFE',
        'PLL',
        'PVH',
        'RBC',
        'RCL',
        'RIO',
        'RTX',
        'SAP',
        'SHC',
        'SIE',
        'SJM',
        'SLI',
        'SQM',
        'STZ',
        'SYM',
        'TLS',
        'TPG',
        'TRP',
        'TRV',
        'TSM',
        'TSN',
        'UNH',
        'VFC',
        'VGT',
        'VOD',
        'VOW',
        'WBX',
        'WDS',
        'WFC',
        'WMT',
        'XOM',
        'AAPL',
        'ABBV',
        'ABNB',
        'ACRV',
        'ADBE',
        'AFLT',
        'ALRS',
        'AMGN',
        'AMZN',
        'ASML',
        'ASPI',
        'ATAT',
        'AVGO',
        'BABA',
        'BAYN',
        'BF-B',
        'BIDU',
        'BIIB',
        'BKNG',
        'BKSY',
        'BLDP',
        'BNTX',
        'BYON',
        'CHPT',
        'COIN',
        'CORN',
        'COST',
        'CSCO',
        'DELL',
        'DWAC',
        'EBAY',
        'ERBB',
        'ESLT',
        'FSLY',
        'GAZP',
        'GBTC',
        'GILD',
        'GMKN',
        'GNLX',
        'GOLD',
        'HTOO',
        'IBIT',
        'IBKR',
        'INTC',
        'JMIA',
        'JUVE',
        'KSCP',
        'KYTX',
        'LAZR',
        'LCID',
        'LKOH',
        'LULU',
        'LYFT',
        'MANU',
        'MBIO',
        'MRNA',
        'MRVL',
        'MSFT',
        'MSTR',
        'NDAQ',
        'NFLX',
        'NKLA',
        'NVAX',
        'NVDA',
        'NVTK',
        'ORCL',
        'PINS',
        'PLTR',
        'PLUG',
        'PYPL',
        'QCOM',
        'RACE',
        'ROSN',
        'SBER',
        'SBUX',
        'SCCO',
        'SGML',
        'SIRI',
        'SITM',
        'SMCI',
        'SNAL',
        'SNAP',
        'SONY',
        'SOUN',
        'SPCE',
        'SPOT',
        'SWKS',
        'TECK',
        'TEVA',
        'TLRY',
        'TRIP',
        'TSLA',
        'UBER',
        'ULTA',
        'UVXY',
        'VALE',
        'VTBR',
        'VXRT',
        'WPRT',
        'WYNN',
        'YNDX',
        'AETUF',
        'BRK-A',
        'FDXTF',
        'GOOGL'
    ],
    ['Stocks']
]
export const marketWatchForex = [
    [
        'AUD/CAD',
        'AUD/CHF',
        'AUD/JPY',
        'AUD/NZD',
        'AUD/USD',
        'CAD/CHF',
        'CAD/JPY',
        'CHF/JPY',
        'EUR/AUD',
        'EUR/CAD',
        'EUR/CHF',
        'EUR/GBP',
        'EUR/JPY',
        'EUR/NZD',
        'EUR/SGD',
        'EUR/USD',
        'GBP/AUD',
        'GBP/CAD',
        'GBP/CHF',
        'GBP/JPY',
        'GBP/NZD',
        'GBP/USD',
        'NZD/CAD',
        'NZD/CHF',
        'NZD/JPY',
        'NZD/USD',
        'USD/CAD',
        'USD/CHF',
        'USD/CNY',
        'USD/HKD',
        'USD/ILS',
        'USD/INR',
        'USD/JPY',
        'USD/MXN',
        'USD/PLN',
        'USD/SGD',
        'USD/TRY',
        'USD/ZAR',
    ],
    [
        'AUDCAD',
        'AUDCHF',
        'AUDJPY',
        'AUDNZD',
        'AUDUSD',
        'CADCHF',
        'CADJPY',
        'CHFJPY',
        'EURAUD',
        'EURCAD',
        'EURCHF',
        'EURGBP',
        'EURJPY',
        'EURNZD',
        'EURSGD',
        'EURUSD',
        'GBPAUD',
        'GBPCAD',
        'GBPCHF',
        'GBPJPY',
        'GBPNZD',
        'GBPUSD',
        'NZDCAD',
        'NZDCHF',
        'NZDJPY',
        'NZDUSD',
        'USDCAD',
        'USDCHF',
        'USDCNY',
        'USDHKD',
        'USDILS',
        'USDINR',
        'USDJPY',
        'USDMXN',
        'USDPLN',
        'USDSGD',
        'USDTRY',
        'USDZAR',
    ],
    ['Forex']
]
export const marketWatchMetals = [
    [
        'Palladium',
        'Platinum',
        'Natural Gas',
        'CRUDE OIL',
        'Silver',
        'Gold',
    ],
    [
        'XPDUSD',
        'XPTUSD',
        'NATGAS',
        'UKOIL',
        'XAGUSD',
        'XAUUSD',
    ],
    ['Metals']
]
